#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
  path: /{_locale}
  controller: App\Controller\AccueilController::accueil
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

contact:
  path: /{_locale}/contact/
  controller: App\Controller\AccueilController::contact
  requirements:
    _locale: '%app.supported_locales%'

boutique:
  path: /{_locale}/boutique/
  controller: App\Controller\BoutiqueController::boutique
  requirements:
    _locale: '%app.supported_locales%'

boutique/rayon:
  path: /{_locale}/boutique/{idCategory}
  controller: App\Controller\BoutiqueController::productsCategory
  requirements:
    _locale: '%app.supported_locales%'

boutique/chercher:
  path: /{_locale}/boutique/chercher/{searchItem}
  controller: App\Controller\AccueilController::searchProducts
  methods: GET
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    searchItem: ''

panier_index:
  path: /{_locale}/panier/
  controller: App\Controller\PanierController::index
  requirements:
    _locale: '%app.supported_locales%'

panier_ajouter:
  path: /{_locale}/panier/ajouter/{idProduit}/{quantite}
  controller: App\Controller\PanierController::ajouter
  requirements:
    _locale: '%app.supported_locales%'

panier_enlever:
  path: /{_locale}/panier/enlever/{idProduit}/{quantite}
  controller: App\Controller\PanierController::enlever
  requirements:
    _locale: '%app.supported_locales%'

panier_supprimer:
  path: /{_locale}/panier/supprimer/{idProduit}
  controller: App\Controller\PanierController::supprimer
  requirements:
    _locale: '%app.supported_locales%'

panier_vider:
  path: /{_locale}/panier/vider
  controller: App\Controller\PanierController::vider
  requirements:
    _locale: '%app.supported_locales%'

panier_validation:
  path: /{_locale}/panier/validation
  controller: App\Controller\PanierController::validation
  requirements:
    _locale: '%app.supported_locales%'

commandes:
  path: /{_locale}/commandes
  controller: App\Controller\UserController::commandes
  requirements:
    _locale: '%app.supported_locales%'

app_user_new:
  path: /{_locale}/signup
  controller: App\Controller\UserController::new
  methods: [GET, POST]
  requirements:
    _locale: '%app.supported_locales%'

app_user_index:
  path: '/{_locale}/compte'
  controller: App\Controller\UserController::index
  methods: GET
  requirements:
    _locale: '%app.supported_locales%'

app_login:
  path: '/{_locale}/login'
  controller: App\Controller\SecurityController::login
  requirements:
    _locale: '%app.supported_locales%'

app_logout:
  path: '/{_locale}/logout'
  controller: App\Controller\SecurityController::logout
  requirements:
    _locale: '%app.supported_locales%'